### ISSUE TITLE
Admin console

### ISSUE THREAD

**Issue by keithstellyes** [keithstellyes/kwitter#1]
A basic CLI application to:

- [x] Add users: #2 
- [x] Remove users: #3
- [x] Add tweets: #4
- [x] Remove tweets: #5
- [x] Add follower #6
- [x] Remove follower #7
- [x] Get all users #8
- [x] Get all followers #9
- [x] Get all tweets #10 
- [ ] Documentation #40
